services:
  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    environment:
      - EXAMPLE_HOST=0.0.0.0
      - EXAMPLE_PORT=41211
  sender:
    build:
      context: .
      dockerfile: sender/Dockerfile
    depends_on:
      - receiver
    environment:
      - EXAMPLE_HOST=receiver
      - EXAMPLE_PORT=41211
