[package]
name = "env"
version = "0.1.0"
edition = "2021"
description = "A library for managing environment variables"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
